#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

THRESHOLD=10000000

FILES=$(git diff --cached --name-only --diff-filter=ACM)

PNPM_LOCK="$(pwd)/pnpm-lock.yaml"

echo $PNPM_LOCK

stat $PNPM_LOCK

echo "./pnpm-lock.yaml"

# for FILE in $FILES
# do
#   echo $FILE
#   FILE_SIZE=$(stat -c %s "$FILE")
#   echo $FILE_SIZE

#   if [ $FILE_SIZE -gt $THRESHOLD ]
#   then
#     echo "Error"
#     exit 1
#   fi
# done

node "$(dirname -- "$0")/compare.js"

exit 1

# exec < /dev/tty && npx cz --hook || true
