name: Github pages

on:
  push:
    branches: [feature/github-action]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Deploy-Github-Page:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: npm run build
      - name: Deploy to aliyun server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FELINE }}
          SOURCE: "dist/"
          REMOTE_HOST: 120.55.48.177
          REMOTE_USER: root
          ALIYUN_TARGET: "/root"
